=== Hydroinformatics/riverscapes-tools-fork/lib/cybercastor/scripts/job.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "taskScriptId": {
      "type": "string"
    },
    "meta": {
      "type": "object"
    },
    "env": {
      "type": "object",
      "properties": {
        "PROGRAM": {
          "type": "string"
        },
        "TAGS": {
          "type": "string"
        }
      },
      "required": [
        "PROGRAM"
      ]
    },
    "resources": {
      "type":"object",
      "properties": {
        "cpu": { "type": "integer"},
        "memory": { "type": "integer"},
        "disk": { "type": "integer"}
      },
      "required": ["cpu", "memory", "disk"]
    },
    "hucs": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "DOCS": {
      "type": "array",
      "items": [
        {
          "type": "string"
        }
      ]
    }
  },
  "required": [
    "$schema",
    "name",
    "taskScriptId",
    "env",
    "hucs"
  ]
}

=== Hydroinformatics/riverscapes-tools-fork/lib/cybercastor/cybercastor/jobs/old/TestStagingRSContext.json
{
  "$schema": "../job.schema.json",
  "name": "Matt Testing Riverscapes-tools Oct 3, 2022",
  "description": "this is a job to do the thing I want to do",
  "taskScriptId": "rs_context_channel_taudem",
  "env": {
    "PROGRAM": "AnabranchDEV",
    "TAGS": "TEST,OCT3"
  },
  "hucs": [
    "17060304",
    "10190002",
    "10190003",
    "10190004"
  ]
}
